# Generated by Django 3.2.9 on 2021-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField(default=None)),
                ('value', models.PositiveBigIntegerField(default=None, max_length=4)),
            ],
        ),
    ]
