# Generated by Django 3.2.9 on 2021-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glucoselevels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='value',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
